cache:
  container_name: iv_cache
  image: redis
api:
  container_name: iv_api
  build: ./images/api/
  volumes:
    - ./api/:/iv_api/
    - ./.git/:/iv_api/.git/
  working_dir: /iv_api/
  command: npm install && npm start
  environment:
    - CACHE_HOST=cache
    - SESSION_SECRET=laskdjfnlaskjdnflkajsdnf
  ports:
    - "8000:3000"
  links:
    - database
    - cache
client:
  container_name: iv_client
  build: ./images/client/
  volumes:
    - ./client/:/iv_client/
  working_dir: /iv_client
  command: npm start
  ports:
  - 3000:3001
  environment:
  - NODE_ENV=development
nginx:
  container_name: iv_nginx
  image: nginx
  volumes:
    - ./images/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    - ./certs/:/etc/nginx/certs
  ports:
    - "80:80"
  links:
    - api
database:
  container_name: iv_db
  image: mongo:4.0
  ports:
    - "27000:27017"
